### ISSUE TITLE
Error with NODEJS project

### ISSUE THREAD

**Issue by marceloau** [loadingio/ldloader#8]
**Method:**
router.post("/download", (request, response) => {
    var ldld = new ldloader({root: ".ldld.full"});
    ldld.on();
    downloadMedia(request.body.url).then(res => {
        request.session.message = {
            type: "success",
            message: "Download da midia realizada com sucesso!"
        };
        response.download(res);
        ldld.off();
    });
});

**DIV on frontend in EJS**
<div class="ldld full"></div>

**Error on log:**
ReferenceError: NodeList is not defined
    at C:\Projetos\DownloadInstagram\node_modules\ldloader\index.min.js:1:427
    at Array.map (<anonymous>)
    at new u (C:\Projetos\DownloadInstagram\node_modules\ldloader\index.min.js:1:348)
    at C:\Projetos\DownloadInstagram\src\app\routes\routes.js:16:6
    at Layer.handle [as handle_request] (C:\Projetos\DownloadInstagram\node_modules\express\lib\router\layer.js:95:5)      
    at next (C:\Projetos\DownloadInstagram\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Projetos\DownloadInstagram\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Projetos\DownloadInstagram\node_modules\express\lib\router\layer.js:95:5)      
    at C:\Projetos\DownloadInstagram\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Projetos\DownloadInstagram\node_modules\express\lib\router\index.js:346:12)

**Comment by zbryikt** [comment]
Hi, this happens because ldLoader uses `NodeList` which exists in frontend but not in NodeJS environment - and that's because ldLoader is designed and expected to be run in frontend context. Since there are other objects used in ldLoader that are only available in frontend ( such as `document` ), I'm not sure if this can be used as the way you want in NodeJS environment. Could you please explain your use case or scenario about ldLoader in backend?

**Comment by zbryikt** [comment]
since there is no other explanation about this issue, we will close it for now.
